// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // CLI（migrate/studio等）はDIRECT_URLがあればそちらを使う。
    // pgbouncer等のコネクションプーラー経由URLをDATABASE_URLに使う場合、
    // マイグレーションはプーラーのプロトコル制限で失敗するため。
    // アプリ実行時の接続は src/lib/prisma.ts が DATABASE_URL を直接参照する
    // （このファイルの datasource.url は使われない）。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
